/*********************************************************************************************
 * @Test Class Name   : ASPGuaranteeTriggerHelperTest
 * @author            : Sanket Saxena(Accenture)
 * @created date      : 10/01/2018
 * @Purpose           : This is the testclass for the class sdgMapper
 **********************************************************************************************/
@isTest

public with sharing class sdgMapperTest {
    @isTest
    static void sdgMapperMethod(){
    
        test.startTest();
        sdgMapper.hack();
        test.stopTest();
    }
}